services:
  priceRunner:
    container_name: priceRunner
    image: bl4ko/price-runner:latest
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}