kumuluzee:
  datasources:
    - jndi-name: jdbc/priceRunner
      connection-url: jdbc:postgresql://localhost:5432/priceRunner
      username: postgres
      password: postgres
      max-pool-size: 20