kumuluzee:
  datasources:
    - jndi-name: jdbc/priceRunner
      connection-url: jdbc:postgresql://localhost:5432/priceRunner
      username: postgres
      password: postgres
      max-pool-size: 20
    # https://github.com/kumuluz/kumuluzee-openapi#accessing-api-specification
  openapi-mp:
    enabled: true
    servlet:
      mapping: /openapi
    ui:
      enabled: true
      mapping: /openapi/ui