name: Git flow

run-name: Check Git flow compliance on branch ${{ github.ref_name }}

# Controls when the workflow will run
on:
  push:
    branches-ignore:
      - main
      - dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      
      - name: Check branch name
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo Checking branch $BRANCH_NAME
          echo $BRANCH_NAME | grep -Ee '\b(feat|fix|chore|docs)/[0-9]+-[a-zA-Z-]+_[a-zA-Z0-9_]+\b'
